import { CSSProperties, ReactNode, useState } from "react";
import { Check, ChevronRight, MessageCircle, Volume2 } from "lucide-react";
import { ttsService } from "../services/ttsService";

type Step = "start" | "vowels" | "verbs" | "negative" | "yesno" | "words" | "introduce" | "exercises" | "time" | "check";
const steps: { id: Step; label: string }[] = [
  { id: "start", label: "Start" }, { id: "vowels", label: "Vowels" }, { id: "verbs", label: "Verbs" },
  { id: "negative", label: "Negative" }, { id: "yesno", label: "Yes / No" }, { id: "words", label: "Question words" },
  { id: "introduce", label: "Introduce" }, { id: "exercises", label: "Exercises" }, { id: "time", label: "Time" }, { id: "check", label: "Check" },
];
const conjugation = [
  ["minä → mä", "puhun", "kysyn", "-n", "mä puhun"], ["sinä → sä", "puhut", "kysyt", "-t", "sä puhut"],
  ["hän → se", "puhuu", "kysyy", "-V", "se puhuu"], ["me", "puhumme", "kysymme", "-mme", "me puhutaan"],
  ["te", "puhutte", "kysytte", "-tte", "te puhutte"], ["he → ne", "puhuvat", "kysyvät", "-vat/-vät", "ne puhuu"],
  ["Te (สุภาพ)", "puhutte", "kysytte", "-tte", "Te puhutte"],
];
const negatives = [
  ["minä → mä", "en", "en puhu", "mä en puhu"], ["sinä → sä", "et", "et puhu", "sä et puhu"],
  ["hän → se", "ei", "ei puhu", "se ei puhu"], ["me", "emme", "emme puhu", "me ei puhuta"],
  ["te", "ette", "ette puhu", "te ette puhu"], ["he → ne", "eivät", "eivät puhu", "ne ei puhu"],
];
const olla = [
  ["minä → mä", "olen", "mä oon", "en ole", "mä en oo"], ["sinä → sä", "olet", "sä oot", "et ole", "sä et oo"],
  ["hän → se", "on", "se on", "ei ole", "se ei oo"], ["me", "olemme", "me ollaan", "emme ole", "me ei olla"],
  ["te", "olette", "te ootte", "ette ole", "te ette oo"], ["he → ne", "ovat", "ne on", "eivät ole", "ne ei oo"],
];
const questionWords = [
  ["kuka", "ใคร", "Kuka sinä olet?", "Olen Olga."], ["mikä", "อะไร (คู่กับ olla/คำนาม)", "Mikä päivä tänään on?", "Tänään on maanantai."],
  ["mitä", "อะไร (กับกริยาอื่น)", "Mitä kieltä sinä puhut?", "Puhun italiaa."], ["milloin", "เมื่อไหร่", "Milloin kurssi on?", "Kurssi on maanantaina."],
  ["minkämaalainen", "สัญชาติอะไร", "Minkämaalainen Pedro on?", "Hän on brasilialainen."], ["missä", "อยู่ที่ไหน", "Missä te asutte?", "Asumme Suomessa."],
  ["mistä", "จากที่ไหน", "Mistä sinä olet kotoisin?", "Olen kotoisin Brasiliasta."], ["mihin", "ไปที่ไหน", "Mihin sinä menet?", "Menen kotiin."],
  ["miksi", "ทำไม", "Miksi et osta jäätelöä?", "Koska säästän rahaa."], ["kuinka", "อย่างไร / เท่าไร", "Kuinka vanha sinä olet?", "Olen 23 vuotta vanha."],
];
const countries = [
  ["Suomi", "suomalainen", "suomi"], ["Ranska", "ranskalainen", "ranska"], ["Kreikka", "kreikkalainen", "kreikka"],
  ["Islanti", "islantilainen", "islanti"], ["Egypti", "egyptiläinen", "arabia"], ["Venäjä", "venäläinen", "venäjä"],
  ["Pakistan", "pakistanilainen", "urdu"], ["Thaimaa", "thaimaalainen", "thai"],
];
const cityExercise = ["Vaasassa", "Jyväskylässä", "Kotkassa", "Kouvolassa", "Mäntsälässä", "Porissa", "Iissä", "Mikkelissä"];
const foodExercise = ["kahvia", "maitoa", "jäätelöä", "kakkua", "sokeria", "keksiä", "pullaa", "mehua"];
const matching = ["minä → ostan", "sinä → laulat", "Jussi → itkee", "me → asumme", "te → nauratte", "Pedro ja Alex → ovat", "minä → etsin", "sinä → rakastat", "te → puhutte", "he → tanssivat", "me → katsomme", "minä → olen", "opettaja → kysyy", "me → istumme"];
const negativeExamples = ["Hän ei puhu englantia.", "Me emme matkusta Tukholmaan.", "Tänään minä en mene kurssille.", "Miksi sinä et osta jäätelöä?", "He eivät asu Suomessa.", "Miksi te ette kysy opettajalta?", "Minä en asu Suomessa.", "Sinä et puhu ruotsia.", "Te ette istu puistossa.", "He eivät osta kahvia.", "Hän ei katso televisiota.", "Minä en naura paljon.", "Me emme säästä rahaa."];
const comprehensive = ["Mikä tämä on?", "Mitä sinä opiskelet?", "Mikä kurssi tämä on?", "Mitä tämä jäätelö maksaa?", "Missä sinä asut?", "Mistä te olette kotoisin?", "Miksi te olette Suomessa?", "Milloin kurssi alkaa?", "Oletteko te kurssilla?", "Asutteko te Suomessa?", "Puhuuko hän japania?", "Etsivätkö he bussipysäkkiä?", "Ettekö te säästä rahaa?", "Asun. / En.", "Puhumme. / Emme.", "Katsovat. / Eivät.", "Maksaa. / Ei."];
const days = [["maanantai", "maanantaina", "Monday"], ["tiistai", "tiistaina", "Tuesday"], ["keskiviikko", "keskiviikkona", "Wednesday"], ["torstai", "torstaina", "Thursday"], ["perjantai", "perjantaina", "Friday"], ["lauantai", "lauantaina", "Saturday"], ["sunnuntai", "sunnuntaina", "Sunday"], ["viikonloppu", "viikonloppuna", "weekend"]];
const timeWords = [["toissapäivänä", "the day before yesterday"], ["eilen", "yesterday"], ["tänään", "today"], ["huomenna", "tomorrow"], ["ylihuomenna", "the day after tomorrow"], ["viime viikolla", "last week"], ["tällä viikolla", "this week"], ["ensi viikolla", "next week"], ["arkipäivä", "weekday"], ["arkisin", "on weekdays"]];
const quiz = [
  ["คำใดต้องใช้ -ko?", ["kurssi", "kieli", "yö"], "kurssi", "kurssi มี u จึงใช้สระหลัง: kurssiko"], ["คำที่มีแค่ i/e เลือก suffix แบบใด?", ["สระหน้า ä/ö/y", "สระหลัง a/o/u", "เลือกได้ทั้งคู่"], "สระหน้า ä/ö/y", "สระกลางล้วนปัดไปใช้ suffix ฝั่งสระหน้า"],
  ["he + puhua คือรูปใด?", ["puhuvat", "puhutte", "puhumme"], "puhuvat", "he ใช้ -vat/-vät"], ["รูปปฏิเสธของ me + puhua คือ?", ["emme puhu", "ei puhu", "ette puhu"], "emme puhu", "กริยาปฏิเสธของ me คือ emme"],
  ["ภาษาพูดของ minä olen คือ?", ["mä oon", "sä oot", "ne on"], "mä oon", "minä → mä และ olen → oon"], ["สร้างคำถามจาก Olet suomalainen", ["Oletko suomalainen?", "Oletkö suomalainen?", "Ko olet suomalainen?"], "Oletko suomalainen?", "ย้ายกริยาหน้าและเติม -ko"],
  ["คำถาม ‘ใคร’ ใช้คำใด?", ["kuka", "mikä", "missä"], "kuka", "kuka = ใคร"], ["ถามว่า ‘จากที่ไหน’ ใช้คำใด?", ["mistä", "missä", "mihin"], "mistä", "mistä = จากที่ไหน"],
  ["ตอบรับ Asutko sinä Helsingissä?", ["Asun.", "Olen.", "En."], "Asun.", "ตอบรับด้วยกริยาที่ผันตามผู้ตอบ"], ["คำว่า vai ใช้แบบใด?", ["ตัวเลือกในคำถาม", "หรือในบอกเล่า", "เพราะว่า"], "ตัวเลือกในคำถาม", "vai ใช้เสนอ A หรือ B ในคำถาม; tai มักใช้ในบอกเล่า"],
  ["‘ใน Jyväskylä’ คือ?", ["Jyväskylässä", "Jyväskylassa", "Jyväskylästa"], "Jyväskylässä", "มี y/ä จึงใช้ -ssä"], ["‘ฉันมาจากกรุงเทพฯ’ คือ?", ["Olen kotoisin Bangkokista.", "Asun Bangkokissa.", "Menen Bangkokiin."], "Olen kotoisin Bangkokista.", "olla kotoisin + -sta/-stä"],
  ["ภาษาไทยหลัง puhua ใช้รูปใด?", ["thaita", "thai", "thaia"], "thaita", "Puhun thaita."], ["‘ในวันพุธ’ คือ?", ["keskiviikkona", "keskiviikossa", "keskiviikko"], "keskiviikkona", "ชื่อวันใช้รูป -na/-nä"],
  ["คำถามฟินแลนด์ลงเสียงอย่างไร?", ["เสียงต่ำท้ายประโยค", "เสียงสูงท้ายประโยค", "ไม่มีหลัก"], "เสียงต่ำท้ายประโยค", "ประโยคบอกเล่าและคำถามของฟินแลนด์มักลงท้ายด้วย falling intonation"],
] as const;

function Finnish({ text, children }: { text: string; children?: ReactNode }) { return <button type="button" className="finnish-speak" onClick={() => ttsService.speak(text)} aria-label={`Listen to ${text}`}>{children ?? text}<Volume2 size={13} /></button>; }
function Grid({ items }: { items: string[] }) { return <div className="lesson3-chip-grid">{items.map(item => <Finnish key={item} text={item} />)}</div>; }
function Table({ headers, rows, audioColumns }: { headers: string[]; rows: string[][]; audioColumns: number[] }) { return <div className="lesson3-table" style={{ "--columns": headers.length } as CSSProperties}><div className="table-head">{headers.map(h => <b key={h}>{h}</b>)}</div>{rows.map((row, i) => <div key={`${row[0]}-${i}`}>{row.map((cell, j) => audioColumns.includes(j) ? <Finnish key={j} text={cell} /> : <span key={j}>{cell}</span>)}</div>)}</div>; }

export function LessonThreePage() {
  const [step, setStep] = useState<Step>("start");
  const [completed, setCompleted] = useState<Step[]>(() => { try { return JSON.parse(localStorage.getItem("sisu:lesson3:v1") || "[]"); } catch { return []; } });
  const [index, setIndex] = useState(0), [answer, setAnswer] = useState(""), [score, setScore] = useState(0), [finished, setFinished] = useState(false);
  const finish = (id: Step) => { const next = [...new Set([...completed, id])]; setCompleted(next); localStorage.setItem("sisu:lesson3:v1", JSON.stringify(next)); };
  const go = (id: Step) => { finish(step); setStep(id); window.scrollTo?.({ top: 0, left: 0, behavior: "auto" }); };
  const q = quiz[index], progress = Math.round(completed.length / steps.length * 100);
  const title = (kicker: string, heading: string, body: string) => <div className="lesson-title"><div><span className="kicker">{kicker}</span><h2>{heading}</h2><p>{body}</p></div><MessageCircle /></div>;
  return <section className="page lesson-page lesson-three">
    <div className="lesson-hero"><div><span className="kicker">LESSON 3 · KAPPALE 2 DEEP DIVE</span><h1>Rakenna suomea</h1><p>ประกอบภาษาฟินแลนด์ให้ถูกต้อง ตั้งแต่สระจนถึงบทสนทนา</p></div><div className="lesson-progress"><b>{progress}%</b><span>complete</span><i><em style={{ width: `${progress}%` }} /></i></div></div>
    <div className="lesson-tabs" role="tablist">{steps.map((s, i) => <button role="tab" aria-selected={step === s.id} className={step === s.id ? "active" : completed.includes(s.id) ? "done" : ""} onClick={() => setStep(s.id)} key={s.id}><span>{completed.includes(s.id) ? <Check size={14} /> : i + 1}</span>{s.label}</button>)}</div>
    {step === "start" && <div className="lesson-panel intro-panel"><div className="lesson-number">03</div><span className="kicker">FINNISH SENTENCE TOOLKIT</span><h2>จากเสียงสระ สู่ประโยคที่ใช้ได้จริง</h2><p>กฎสระ · การผันกริยา · ประโยคคำถาม · การแนะนำตัว · วันและเวลา พร้อมเฉลยแบบฝึกหัดจากต้นฉบับทุกชุด</p><div className="objectives"><div><span>01</span><p><b>เลือกคำต่อท้าย</b>เข้าใจสระหลัง สระหน้า สระกลาง และคำประสม</p></div><div><span>02</span><p><b>สร้างประโยค</b>ผันกริยา บอกเล่า ปฏิเสธ และคำถาม</p></div><div><span>03</span><p><b>ใช้จริง</b>แนะนำตัว ถามข้อมูล และตอบอย่างเป็นธรรมชาติ</p></div></div><button className="primary lesson-next" onClick={() => go("vowels")}>เริ่มจากกฎสระ <ChevronRight /></button></div>}
    {step === "vowels" && <div className="lesson-panel">{title("VOKAALIHARMONIA", "ความกลมกลืนของสระ", "ดูสระทั้งคำ ไม่ใช่เฉพาะตัวท้าย; ยกเว้นคำประสมให้ดูส่วนประกอบสุดท้าย")}<div className="vowel-groups"><article className="back"><b>a · o · u</b><span>สระหลัง</span><p>อยู่กับ i/e ได้ และเลือก suffix ฝั่ง a/o/u</p></article><article className="neutral"><b>i · e</b><span>สระกลาง</span><p>อยู่กับทุกกลุ่ม; ถ้าอยู่ล้วนๆ ใช้ suffix ฝั่ง ä/ö/y</p></article><article className="front"><b>ä · ö · y</b><span>สระหน้า</span><p>ไม่อยู่กับ a/o/u ในคำเดี่ยว และเลือก suffix ฝั่ง ä/ö/y</p></article></div><h3>คู่คำต่อท้ายสำคัญ</h3><div className="suffix-grid">{[["-ssa / -ssä", "ใน"], ["-sta / -stä", "จาก"], ["-lla / -llä", "ที่/ด้วย"], ["-na / -nä", "ในฐานะ/ในวัน"], ["-ko / -kö", "คำถาม"], ["-vat / -vät", "พวกเขา"], ["-a / -ä", "partitive"]].map(([a,b]) => <article key={a}><b>{a}</b><span>{b}</span></article>)}</div><h3>ตัดสินจากทั้งคำ</h3><div className="example-flow"><article><Finnish text="kurssi" /><span>มี u แม้ลงท้าย i</span><Finnish text="kurssiko" /></article><article><Finnish text="kieli" /><span>มีแต่ i/e</span><Finnish text="kielikö" /></article><article><Finnish text="tuoli" /><span>มี u/o</span><Finnish text="tuolissa" /></article><article><Finnish text="kaappi" /><span>มี a</span><Finnish text="kaapissa" /></article></div><div className="lesson-tip"><b>คำประสม — Yhdyssanat</b><p><Finnish text="suklaajäätelössä" /> ดูคำท้าย jäätelö → -ssä · <Finnish text="jäätelökioskilla" /> ดูคำท้าย kioski ซึ่งมี o → -lla</p></div><h3>Tuleeko -vat vai -vät?</h3><Grid items={["kysyvät", "etsivät", "löytävät", "sanovat", "tutustuvat", "maksavat", "säästävät", "puhuvat", "tietävät", "istuvat"]} /><button className="primary lesson-next" onClick={() => go("verbs")}>ต่อไป: การผันกริยา <ChevronRight /></button></div>}
    {step === "verbs" && <div className="lesson-panel">{title("VERBIN PERSOONATAIVUTUS", "กริยาเปลี่ยนตามประธาน", "puhua = พูด, kysyä = ถาม; -V หมายถึงยืดสระท้ายของรากคำ")}<Table headers={["ประธาน", "puhua", "kysyä", "คำลงท้าย", "ภาษาพูด"]} rows={conjugation} audioColumns={[0,1,2,4]} /><h3>กริยาพิเศษ olla — เป็น / อยู่ / คือ</h3><Table headers={["ประธาน", "เขียน", "พูด", "ปฏิเสธ", "พูดปฏิเสธ"]} rows={olla} audioColumns={[0,1,2,3,4]} /><div className="lesson-tip"><b>จุดสังเกต</b><p>ภาษาพูดใช้ se แทน hän, ne แทน he; me puhutaan / me ollaan และ ne puhuu / ne on พบได้บ่อยมาก</p></div><button className="primary lesson-next" onClick={() => go("negative")}>ต่อไป: ประโยคปฏิเสธ <ChevronRight /></button></div>}
    {step === "negative" && <div className="lesson-panel">{title("NEGATIIVINEN LAUSE", "ประโยคปฏิเสธ", "กริยาปฏิเสธผันตามประธาน + กริยาหลักรูปหางกุด")}<div className="formula"><b>puhua</b><span>ตัด -a</span><b>puhu</b><span>→</span><b>en puhu</b></div><Table headers={["ประธาน", "กริยาปฏิเสธ", "ภาษาเขียน", "ภาษาพูด"]} rows={negatives} audioColumns={[0,1,2,3]} /><h3>ตัวอย่างครบชุด</h3><Grid items={negativeExamples} /><div className="lesson-tip"><b>อย่าสับสนกับรูป minä</b><p>กริยาหลักในประโยคปฏิเสธไม่ใช่รูป minä: <strong>et puhu</strong> ไม่ใช่ et puhun; <strong>ei asu</strong> ไม่ใช่ ei asuu</p></div><button className="primary lesson-next" onClick={() => go("yesno")}>ต่อไป: คำถาม Yes / No <ChevronRight /></button></div>}
    {step === "yesno" && <div className="lesson-panel">{title("KO/KÖ-KYSYMYS", "คำถามใช่หรือไม่", "ย้ายกริยามาหน้าสุด เติม -ko/-kö ตามกฎสระ; ถ้าปฏิเสธให้ย้ายกริยาปฏิเสธ")}<div className="transform-list"><article><span>Sinä olet suomalainen.</span><b>→</b><Finnish text="Oletko sinä suomalainen?" /></article><article><span>Hän asuu Suomessa.</span><b>→</b><Finnish text="Asuuko hän Suomessa?" /></article><article><span>Sinä et puhu englantia.</span><b>→</b><Finnish text="Etkö sinä puhu englantia?" /></article></div><h3>ภาษาพูด: -ko/-kö มักย่อเป็น -ks</h3><Grid items={["Ooks sä suomalainen?", "Asuuks se Suomessa?", "Eks sä puhu englantia?"]} /><h3>ตอบด้วยการทวนกริยา</h3><div className="answer-pairs"><article><Finnish text="Asutko sinä Helsingissä?" /><p><b>ใช่:</b> Asun. · <b>ไม่:</b> En.</p></article><article><Finnish text="Puhutteko englantia?" /><p><b>ใช่:</b> Puhumme. · <b>ไม่:</b> Emme.</p></article></div><div className="lesson-tip"><b>vai กับ tai</b><p><strong>vai</strong> = หรือ ในคำถามที่ให้เลือก: vat vai vät? ส่วน <strong>tai</strong> มักใช้ “หรือ” ในประโยคบอกเล่า</p></div><div className="lesson-tip"><b>Intonaatio</b><p>ประโยคบอกเล่า คำถาม -ko/-kö และ Wh-question ของฟินแลนด์ลงท้ายด้วยเสียงต่ำ ไม่ตวัดสูงแบบอังกฤษ</p></div><button className="primary lesson-next" onClick={() => go("words")}>ต่อไป: คำแสดงคำถาม <ChevronRight /></button></div>}
    {step === "words" && <div className="lesson-panel">{title("KYSYMYSSANAT", "คำแสดงคำถาม", "โครงสร้างพื้นฐาน: คำถาม + ประธาน + กริยา")}<Table headers={["คำถาม", "ความหมาย", "ตัวอย่าง", "คำตอบ"]} rows={questionWords} audioColumns={[0,2,3]} /><div className="lesson-tip"><b>mikä หรือ mitä?</b><p><strong>mikä</strong> มักถามตัวตน/ประเภทคู่กับ olla หรือคำนาม: Mikä tämä on? · <strong>mitä</strong> ใช้กับการกระทำ: Mitä opiskelet?</p></div><div className="formula"><b>Kuka</b><span>+</span><b>sinä</b><span>+</span><b>olet?</b></div><button className="primary lesson-next" onClick={() => go("introduce")}>ต่อไป: แนะนำตัว <ChevronRight /></button></div>}
    {step === "introduce" && <div className="lesson-panel">{title("MINÄ JA KIELET", "แนะนำตัว ประเทศ สัญชาติ ภาษา", "ชื่อประเทศใช้ตัวพิมพ์ใหญ่ แต่สัญชาติและภาษาใช้ตัวพิมพ์เล็ก")}<div className="profile-example"><span>PH</span><div><Finnish text="Minä olen Phawit." /><Finnish text="Olen thaimaalainen." /><Finnish text="Olen kotoisin Bangkokista, Thaimaasta." /><Finnish text="Puhun thaita." /><Finnish text="Puhun thaita ja englantia." /></div></div><h3>สามคำถามหลัก</h3><div className="answer-pairs"><article><Finnish text="Mistä sinä olet kotoisin?" /><p>olla kotoisin + -sta/-stä: Suomesta, Egyptistä; Venäjä ใช้ Venäjältä</p></article><article><Finnish text="Minkämaalainen sinä olet?" /><p>สัญชาติมักลงท้าย -lainen/-läinen</p></article><article><Finnish text="Mitä kieltä sinä puhut?" /><p>ภาษาหลัง puhua อยู่รูป partitive: suomea, ranskaa, venäjää, thaita</p></article></div><Table headers={["Maa · ประเทศ", "Kansalaisuus · สัญชาติ", "Kieli · ภาษา"]} rows={countries} audioColumns={[0,1,2]} /><h3>ตัวอย่างจากหนังสือ</h3><div className="intro-people"><article><b>Pedro</b><Finnish text="Minä olen Pedro. Olen brasilialainen. Olen kotoisin São Paulosta Brasiliasta. Puhun portugalia." /></article><article><b>Olga</b><Finnish text="Minun nimeni on Olga. Olen venäläinen. Olen kotoisin Pietarista Venäjältä. Puhun venäjää. En puhu englantia." /></article><article><b>Alex</b><Finnish text="Minä olen Alex. Olen eteläafrikkalainen. Olen kotoisin Johannesburgista, Etelä-Afrikasta. Minun äidinkieleni on englanti. Puhun myös vähän espanjaa." /></article></div><button className="primary lesson-next" onClick={() => go("exercises")}>ต่อไป: เฉลยแบบฝึกหัด <ChevronRight /></button></div>}
    {step === "exercises" && <div className="lesson-panel">{title("HARJOITUKSET 6 · 16 · 20–21 · 23–27", "แบบฝึกหัดพร้อมเฉลย", "ทบทวนกฎสระ การผันกริยา ปฏิเสธ และคำถามครบทุกชุดที่มีในต้นฉบับ")}<h3>Harjoitus 6A · เติม -ssa/-ssä ให้ชื่อเมือง</h3><Grid items={cityExercise} /><h3>Harjoitus 6B · เติม -a/-ä ให้คำอาหาร</h3><Grid items={foodExercise} /><h3>Harjoitus 16 · จับคู่ประธานกับกริยา</h3><Grid items={matching} /><h3>Harjoitus 20–21 · ประโยคปฏิเสธ</h3><Grid items={negativeExamples} /><h3>Harjoitus 23–27 · คำถามและคำตอบ</h3><Grid items={comprehensive} /><div className="lesson-tip"><b>ลำดับคิด</b><p>หา subject → ผันกริยา → เลือก suffix ตามสระ → ถ้าเป็นคำถามย้ายกริยาไว้หน้า → ถ้าปฏิเสธใช้ en/et/ei/emme/ette/eivät</p></div><button className="primary lesson-next" onClick={() => go("time")}>ต่อไป: วันและเวลา <ChevronRight /></button></div>}
    {step === "time" && <div className="lesson-panel">{title("VIIKONPÄIVÄT · AIKA", "วันในสัปดาห์และเวลา", "เมื่อหมายถึง “ในวัน…” ใช้ -na/-nä; ชื่อวันทั้งหมดในชุดนี้ใช้ -na")}<div className="day-grid">{days.map(([base, form, en]) => <article key={base}><Finnish text={base} /><Finnish text={form} /><p>{en}</p></article>)}</div><Grid items={["Mikä päivä tänään on?", "Milloin kurssi on?", "Hyvää viikonloppua"]} /><h3>อดีต · ปัจจุบัน · อนาคต</h3><div className="useful-grid">{timeWords.map(([fi, en]) => <article key={fi}><Finnish text={fi} /><span>{en}</span></article>)}</div><div className="lesson-tip"><b>จำคำว่า viikko</b><p>viime viikolla = สัปดาห์ที่แล้ว · tällä viikolla = สัปดาห์นี้ · ensi viikolla = สัปดาห์หน้า</p></div><button className="primary lesson-next" onClick={() => go("check")}>ทำแบบทดสอบ 15 ข้อ <ChevronRight /></button></div>}
    {step === "check" && <div className="lesson-panel quiz-panel"><span className="kicker">KNOWLEDGE CHECK</span><h2>ทบทวน Lesson 3</h2>{finished ? <div className="lesson-result"><span>✓</span><div><p>จบบทเรียนแล้ว</p><b>{score} / {quiz.length}</b><p>{score >= 12 ? "Hienoa! พร้อมนำไปใช้จริง" : "Hyvä yritys! กลับไปทบทวนจุดที่ยังสับสนได้"}</p></div></div> : <><p>คำถาม {index + 1} จาก {quiz.length}</p><h3>{q[0]}</h3><div className="lesson-answers">{q[1].map(choice => <button key={choice} disabled={!!answer} className={answer ? choice === q[2] ? "correct" : choice === answer ? "wrong" : "" : ""} onClick={() => { setAnswer(choice); if (choice === q[2]) setScore(s => s + 1); }}>{choice}</button>)}</div>{answer && <><div className="lesson-tip"><b>{answer === q[2] ? "Oikein! ถูกต้อง" : "ยังไม่ถูก"}</b><p>{q[3]}</p></div><button className="primary lesson-next" onClick={() => { if (index === quiz.length - 1) { setFinished(true); finish("check"); } else { setIndex(i => i + 1); setAnswer(""); window.scrollTo?.({ top: 0, left: 0, behavior: "auto" }); } }}>คำถามถัดไป <ChevronRight /></button></>}</>}</div>}
  </section>;
}
