import { useState } from 'react';
import { Check, ChevronRight, Volume2 } from 'lucide-react';
import { ttsService } from '../services/ttsService';
import vocabulary from '../data/lessonFiveVocabulary.json';
import { bookPages } from '../data/lessonFiveBook';
import { BookExercises, BookVocabulary } from './LessonFiveBook';
import { files, homework, moodleSource, pictures, quiz, quizletSources, reading, readingVocabulary, translations } from '../data/lessonFiveContent';

const steps = ['Start', 'Seasons', 'Weather', 'Adjectives', 'Colours', 'Reading', 'Pictures', 'Book', 'Translation', 'Homework', 'Check', 'Files'] as const;
type Step = typeof steps[number];
const storageKey = 'sisu:lesson5:v1';
function savedList(key: string): string[] {
  try { const value: unknown = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value.filter((v): v is string => typeof v === 'string') : []; }
  catch { return []; }
}
function Speak({ text }: { text: string }) {
  const [error, setError] = useState(false);
  return <><button type="button" className="finnish-speak" lang="fi" aria-label={`Listen to ${text}`} onClick={() => { setError(false); if (!ttsService.speak(text, undefined, () => setError(true))) setError(true); }}>{text}<Volume2 size={13} /></button>{error && <small role="status">ไม่พบเสียงฟินแลนด์ กรุณาตรวจการตั้งค่าเสียง</small>}</>;
}
function Words({ name }: { name: keyof typeof vocabulary }) {
  return <div className="lesson5-vocabulary">{vocabulary[name].map((word, i) => <article key={`${word.fi}-${i}`}><Speak text={word.fi} /><p>{word.th}</p><small>{word.en}</small></article>)}</div>;
}
export function LessonFivePage() {
  const [step, setStep] = useState<Step>('Start');
  const [completed, setCompleted] = useState(() => savedList(storageKey).filter(v => steps.includes(v as Step)));
  const [tasks, setTasks] = useState(() => savedList(`${storageKey}:homework`));
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [saveError, setSaveError] = useState(false);
  const save = (key: string, value: string[]) => { try { localStorage.setItem(key, JSON.stringify(value)); setSaveError(false); } catch { setSaveError(true); } };
  const finish = () => { const next = [...new Set([...completed, step])]; setCompleted(next); save(storageKey, next); };
  const go = (next: Step) => { setStep(next); window.scrollTo?.({ top: 0, behavior: 'auto' }); };
  const progress = Math.round(completed.length / steps.length * 100);
  const draft = (id: string, label: string) => <label className="lesson5-draft">{label}<textarea value={drafts[id] || ''} onChange={e => setDrafts(d => ({ ...d, [id]: e.target.value }))} rows={3} placeholder="เขียนเป็นภาษาฟินแลนด์…" /></label>;
  const allAnswered = Object.keys(answers).length === quiz.length;
  const score = quiz.filter((q, i) => answers[i] === q[2]).length;
  return <section className="page lesson-page lesson-three lesson-five">
    <div className="lesson-hero"><div><span className="kicker">LESSON 05 · SELF-STUDY · 01.10.2026</span><h1>Vuodenajat ja sää</h1><p>ฤดูกาล สภาพอากาศ คำคุณศัพท์ และสี — เรียนด้วยตัวเองจาก Moodle</p></div><div className="lesson-progress"><b>{progress}%</b><span>complete</span><i><em style={{ width: `${progress}%` }} /></i></div></div>
    <div className="lesson-tabs" role="tablist" aria-label="Lesson 5 sections">{steps.map((s, i) => <button type="button" role="tab" id={`lesson5-tab-${s}`} aria-controls="lesson5-panel" aria-selected={s === step} key={s} className={s === step ? 'active' : completed.includes(s) ? 'done' : ''} onClick={() => go(s)}><span>{completed.includes(s) ? <Check size={14} /> : i + 1}</span>{s}</button>)}</div>
    <div className="lesson-panel" role="tabpanel" id="lesson5-panel" aria-labelledby={`lesson5-tab-${step}`}>
      {step === 'Start' && <><span className="kicker">VUODENAJAT SUOMESSA</span><h2>เรียนเรื่องอากาศและชีวิตในแต่ละฤดู</h2><p>เนื้อหาตามบทเรียนวันพฤหัสบดีที่ 1 ตุลาคม 2026: คำศัพท์ Quizlet 4 ชุด รวม 95 รายการ บทอ่านครบ 4 ฤดู ไฟล์เสียง track 1-33 ภาพฝึก 6 ภาพ และโจทย์แปล 7 ข้อพร้อมเฉลยผู้สอน เพิ่มเนื้อหาหนังสือหน้า 60–62 พร้อมแบบฝึก 9 (หน้า 73), 12 (หน้า 75), 23 (หน้า 81) และเฉลยท้ายเล่มหน้า 331 ครบแล้ว</p><div className="objectives"><div><span>01</span><p><b>บอกเวลาและอากาศ</b>รู้จักชื่อเดือน ฤดู ช่วงเวลา อุณหภูมิ และปรากฏการณ์อากาศ</p></div><div><span>02</span><p><b>อ่าน ฟัง และแปล</b>เข้าใจคำศัพท์จากเรื่อง Vuodenajat Suomessa และใช้เขียนประโยค</p></div><div><span>03</span><p><b>ฝึกและตรวจด้วยตัวเอง</b>บรรยายภาพ ทบทวนประโยคปฏิเสธ และติดตามการบ้าน</p></div></div><div className="lesson-tip"><b>วิธีเรียน</b><p>เริ่มจากคำศัพท์ → อ่านพร้อมฟัง → ลองบรรยายภาพและแปลก่อนเปิดเฉลย → ทำแบบฝึกในหนังสือ → ทดสอบตัวเอง ปุ่มลำโพงเป็นเสียงสังเคราะห์ ส่วน Reading มีไฟล์เสียงต้นฉบับ</p><p>กด “ทำส่วนนี้เสร็จแล้ว” เพื่อบันทึกความคืบหน้า การเปิดแท็บอย่างเดียวไม่ถือว่าทำเสร็จ ช่องร่างคำตอบเก็บระหว่างเปิดบทเรียนนี้ ส่วนเช็กลิสต์เก็บในอุปกรณ์</p></div><a href={moodleSource} target="_blank" rel="noreferrer">เปิดคำสั่งบทเรียนต้นฉบับใน Moodle</a></>}
      {step === 'Seasons' && <><h2>Vuodenajat, kuukaudet ja vuorokausi</h2><p>ฤดูกาล เดือน และช่วงเวลาของวัน · ตาม Quizlet 27 รายการ · ตรวจเทียบหนังสือหน้า 62 แล้ว</p><div className="lesson-tip"><b>Milloin? — เมื่อไร?</b><p>ฤดูใช้ talvella, keväällä, kesällä, syksyllä ส่วนเดือนใช้ -ssa: tammikuu → tammikuussa ชื่อเดือนและฤดูเขียนตัวเล็ก ยกเว้นต้นประโยค</p><p>aamu → aamulla, ilta → illalla, yö → yöllä; vuorokausi หมายถึง 24 ชั่วโมงเต็ม ส่วน päivä อาจหมายถึงวันหรือกลางวัน</p></div><Words name="seasons" /><h3>ลองประกอบประโยค</h3><Speak text="Talvella on kylmä. Toukokuussa on lämmin. Illalla olen kotona." /><p>ในฤดูหนาวอากาศหนาว ในเดือนพฤษภาคมอากาศอบอุ่น ตอนเย็นฉันอยู่บ้าน</p></>}
      {step === 'Weather' && <><h2>Sää — สภาพอากาศ</h2><p>คำศัพท์และประโยคจาก Quizlet ครบ 30 รายการ · งานอ้างถึงหน้า 61 และแบบฝึก 12 หน้า 75</p><Words name="weather" /><div className="lesson-tip"><b>รูปแบบประโยคที่ต้องใช้</b><p>On + คำบรรยาย: On kylmä. / On pilvistä. กริยาอากาศใช้ได้โดยไม่ต้องมีประธาน: Sataa. / Tuulee. แต่ Aurinko paistaa. มี aurinko เป็นประธาน</p><p>ฝนตก: Sataa vettä. หิมะตก: Sataa lunta. ฝนปนหิมะ: Sataa räntää. ปฏิเสธฝนตก: Ei sada. ปฏิเสธความหนาว: Ei ole kylmä.</p><p>+1 °C = yksi aste lämmintä; +13 °C = kolmetoista astetta lämmintä; −25 °C = kaksikymmentäviisi astetta pakkasta. หลังจำนวนมากกว่า 1 ใช้ astetta</p><p>pouta คือสภาพที่ไม่มีฝน ไม่ได้หมายความว่าต้องแดดจัด ส่วน helle หมายถึงอากาศร้อนจัด</p></div></>}
      {step === 'Adjectives' && <><h2>Millainen? — เป็นอย่างไร?</h2><p>คำคุณศัพท์และคำบอกปริมาณจาก Quizlet 22 รายการ (ต้นฉบับมี kylmä ซ้ำ 2 ครั้ง) · งานหน้า 60 และแบบฝึก 9 หน้า 73</p><Words name="adjectives" /><h3>จำเป็นคู่ตรงข้าม</h3><p>hyvä ↔ huono · kuuma ↔ kylmä · vaikea ↔ helppo · pieni ↔ suuri/iso · uusi ↔ vanha · kaunis ↔ ruma · lämmin ↔ viileä · valoisa ↔ pimeä · lyhyt ↔ pitkä · paljon ↔ vähän</p><div className="lesson-tip"><b>อ่านรูปคำให้ถูก</b><p>คำแรกคือรูปพื้นฐาน คำที่สองในรายการเป็น genitive เช่น lämmin → lämpimän, uusi → uuden, helppo → helpon เพื่อให้เห็นรูปคำเมื่อผัน ไม่ต้องเติม -n ในประโยค Sää on lämmin.</p><p>paljon และ vähän เป็นคำบอกปริมาณ ใช้ต่างจากคำคุณศัพท์ เช่น paljon lunta = หิมะมาก, vähän aikaa = เวลาน้อย</p></div><Speak text="Talvella päivä on lyhyt ja yö on pitkä. Tämä harjoitus ei ole vaikea." /><p>ฤดูหนาวกลางวันสั้นและกลางคืนยาว แบบฝึกนี้ไม่ยาก</p></>}
      {step === 'Colours' && <><h2>Värit — สี</h2><p>Quizlet ครบ 16 รายการ รวมคำถามเรื่องสีและรูปผัน · เป็นส่วนหนึ่งของการบ้าน</p><Words name="colours" /><div className="lesson-tip"><b>Minkävärinen? — สีอะไร?</b><p>Minkävärinen takki sinulla on? = คุณมีเสื้อแจ็กเก็ตสีอะไร? ตัวอย่างคำตอบ: Minulla on sininen takki.</p><p>สี่รูปที่แสดง เช่น sininen, sinisen, sinistä, sinisiä คือรูปพื้นฐาน, genitive เอกพจน์, partitive เอกพจน์, partitive พหูพจน์ ตามลำดับ เริ่มจำรูปพื้นฐานก่อน แล้วสังเกต -nen → -se- ในรูป sinisen</p><p>tumma = เข้ม; vaalea = อ่อน: tummansininen = น้ำเงินเข้ม, vaaleanpunainen = ชมพูอ่อน</p></div><Speak text="Syksyn värit ovat punainen, keltainen, oranssi ja ruskea." /></>}
      {step === 'Reading' && <><h2>Vuodenajat Suomessa — อ่านและฟัง</h2><p>บทอ่านถอดจาก PDF ของผู้สอน คำแปลไทยและคำอธิบายเพิ่มเพื่อการเรียน</p><audio controls preload="metadata" aria-label="Vuodenajat Suomessa — track 1-33" src="/lesson5/1-33-vuodenajat-suomessa.mp3" /><p><a href="/lesson5/1-33-vuodenajat-suomessa.mp3" download>ดาวน์โหลดเสียง track 1-33</a> · <a href="/lesson5/vuodenajat-suomessa.pdf" target="_blank" rel="noreferrer">เปิด PDF ต้นฉบับ</a></p>{reading.map(part => <article className="lesson5-reading" key={part.title}><h3>{part.title}</h3>{part.lines.map(([fi, th]) => <div key={fi}><Speak text={fi} /><p>{th}</p></div>)}</article>)}<div className="lesson-tip"><p>ข้อความเรื่องแสงสว่างเพียงสองสามชั่วโมงเป็นคำบรรยายในต้นฉบับ ระยะเวลากลางวันจริงแตกต่างตามเดือนและพื้นที่ของฟินแลนด์</p></div><h3>คำศัพท์ช่วยอ่าน</h3><div className="lesson5-vocabulary">{readingVocabulary.map(([fi, th]) => <article key={fi}><b lang="fi">{fi}</b><p>{th}</p></article>)}</div><h3>ฟัง 3 รอบ</h3><ol><li>ฟังโดยไม่อ่าน จับชื่อฤดูทั้งสี่</li><li>ฟังพร้อมอ่าน สังเกตคำบอกเดือนและกริยากิจกรรม</li><li>หยุดหลังแต่ละฤดู แล้วเล่า 2 ประโยคด้วยคำของตัวเอง</li></ol><details><summary>ดูหน้าต้นฉบับ</summary><img className="lesson5-source-image" src="/lesson5/vuodenajat-suomessa.png" alt="หน้าบทอ่านต้นฉบับ Vuodenajat Suomessa" loading="lazy" /></details></>}
      {step === 'Pictures' && <><h2>Kuvaile säätä — บรรยายอากาศจากภาพ</h2><p>ภาพต้นฉบับทั้ง 6 ภาพ เรียงซ้ายไปขวา ทีละแถว ให้บอกสภาพอากาศและอุณหภูมิ ตัวอย่างคำตอบด้านล่างเขียนเพิ่มเพื่อฝึก ไม่ใช่เฉลยจากผู้สอน</p><img className="lesson5-source-image" src="/lesson5/weather-pictures.png" alt="ภาพอากาศ 6 ภาพ: ฝน +13, ฝนปนหิมะ +1, หาดแดดจัด +34, หิมะ −25, ลมแรง +27, ฟ้าแลบ +19 องศาเซลเซียส" />{pictures.map(([label, fi, th], i) => <article className="lesson5-exercise" key={label}><h3>{label}</h3>{draft(`picture-${i}`, `คำบรรยายภาพ ${i + 1}`)}<details><summary>ดูตัวอย่างคำบรรยาย</summary><Speak text={fi} /><p>{th}</p></details></article>)}<p>ภาพที่มีหิมะบนพื้นไม่ได้แปลว่าขณะนั้นหิมะกำลังตก ใช้ Maassa on lunta. เมื่อเห็นหิมะอยู่บนพื้น</p></>}
      {step === 'Book' && <BookExercises speak={text => <Speak text={text} />} draft={draft} />}
      {step === 'Translation' && <><h2>Käännä suomeksi — แปลเป็นภาษาฟินแลนด์</h2><p>โจทย์ภาษาอังกฤษและเฉลยทั้ง 7 ข้อจากไฟล์ DOCX ของผู้สอน คำแปลไทยและคำอธิบายไวยากรณ์เป็นเนื้อหาเสริม ลองเขียนก่อนเปิดเฉลย</p>{translations.map(([en, th, fi, note], i) => <article className="lesson5-exercise" key={en}><h3>ข้อ {i + 1}</h3><p>{en}</p><p>{th}</p>{draft(`translation-${i}`, `คำแปลข้อ ${i + 1}`)}<details><summary>ดูเฉลยผู้สอนและคำอธิบาย</summary><Speak text={fi} /><p>{note}</p></details></article>)}<div className="lesson-tip"><b>รูปแบบที่ควรจำ</b><p>รักหรือรอสิ่งใด: rakastan talvea / odotan kesää. อยู่ที่ไหน: kotona / puistossa / kesämökillä. ไปที่ไหน: saunaan / metsään.</p></div></>}
      {step === 'Homework' && <><h2>การบ้านและงานเรียนด้วยตัวเอง</h2><p>รายการทั้งหมดจากหน้า Moodle ทำเสร็จแล้วติ๊กไว้ได้</p><div className="lesson5-checklist">{homework.map((task, i) => <label key={task}><input type="checkbox" checked={tasks.includes(String(i))} onChange={() => { const next = tasks.includes(String(i)) ? tasks.filter(t => t !== String(i)) : [...tasks, String(i)]; setTasks(next); save(`${storageKey}:homework`, next); }} /><span>{task}</span></label>)}</div><div className="lesson-tip"><b>แบบฝึกจากหนังสือครบแล้ว</b><p>เพิ่มเนื้อหาหน้า 60–62 และโจทย์จริงแบบฝึก 9 หน้า 73, แบบฝึก 12 หน้า 75, แบบฝึก 23 หน้า 81 พร้อมเฉลยจากหน้า 331 เลขทั้งหมดอ้างอิงเลขหน้าที่พิมพ์ในหนังสือ</p><button type="button" className="primary" onClick={() => go("Book")}>เปิดแบบฝึกจากหนังสือ</button></div><h3>แบบฝึกเสริม: บอกเล่า → ปฏิเสธ</h3><p>ทบทวนเพิ่มเติมหลังทำแบบฝึก 23 (ตัวอย่างต่อไปนี้เขียนเพิ่ม แยกจากโจทย์จริงในแท็บ Book)</p>{[['Lapset hiihtävät.', 'Lapset eivät hiihdä.'], ['He uivat.', 'He eivät ui.'], ['Minä katson televisiota.', 'Minä en katso televisiota.'], ['Me olemme kotona.', 'Me emme ole kotona.'], ['Aurinko paistaa.', 'Aurinko ei paista.']].map(([fi, answer]) => <details className="lesson5-exercise" key={fi}><summary>{fi}</summary><Speak text={answer} /></details>)}<p>en / et / ei / emme / ette / eivät + รูปกริยาปฏิเสธ เช่น eivät ui ไม่ใช่ eivät uivat; olla ใช้ ole</p></>}
      {step === 'Check' && <><h2>ทบทวนความเข้าใจ</h2><p>แบบทดสอบเสริม 12 ข้อ เลือกได้ข้อละครั้ง แล้วอ่านคำอธิบาย ลองใหม่ได้เมื่อทำครบ</p>{quiz.map(([question, options, correct, note], i) => <fieldset className="lesson5-exercise" key={question}><legend>{i + 1}. {question}</legend><div className="lesson5-options">{options.map(option => <button type="button" key={option} disabled={answers[i] !== undefined} aria-pressed={answers[i] === option} className={answers[i] === option ? 'active' : ''} onClick={() => setAnswers(a => ({ ...a, [i]: option }))}>{option}</button>)}</div>{answers[i] !== undefined && <p role="status">{answers[i] === correct ? '✓ ถูกต้อง' : `ลองจำใหม่ — คำตอบ: ${correct}`} · {note}</p>}</fieldset>)}{allAnswered && <div className="lesson-tip"><b>คะแนน {score} / {quiz.length}</b><p>ทบทวนคำอธิบายข้อที่ยังไม่แม่น แล้วฝึกซ้ำได้</p><button type="button" className="primary" onClick={() => setAnswers({})}>เริ่มแบบทดสอบใหม่</button></div>}</>}
      {step === 'Files' && <><h2>ไฟล์ต้นฉบับและแหล่งเนื้อหา</h2><p>ตรวจเนื้อหาเมื่อ 4 ตุลาคม 2026 · ไฟล์แนบจาก Moodle ดาวน์โหลดครบ 4 รายการ</p><div className="lesson5-files">{files.map(([title, path, id]) => <article key={path}><a href={`/lesson5/${path}`} download>{title}</a><a href={`https://moodle.abo.fi/mod/resource/view.php?id=${id}`} target="_blank" rel="noreferrer">แหล่งต้นฉบับ Moodle</a></article>)}</div><h3>หนังสือ Suomen mestari 1 — หน้าที่ใช้ในบทเรียน</h3><p>ตรวจจากไฟล์ Suomen_mestari_1.pdf ที่ให้มา โดยอ่านเลขหน้าพิมพ์บนกระดาษ หน้า 60 ตรงกับหน้าลำดับ 59 ของไฟล์ เช่นเดียวกับหน้าที่ตรวจด้านล่าง</p><div className="lesson5-files">{bookPages.map(({ printed, filePage, title }) => <article key={printed}><a href={`/lesson5/book/page-${printed}.jpg`} target="_blank" rel="noreferrer">หน้าหนังสือ {printed} · {title}</a><small>ลำดับหน้าใน PDF ต้นฉบับ: {filePage} · ภาพครบหน้าจากไฟล์ที่ให้มา</small></article>)}</div><h3>Quizlet — อ่านครบทั้ง 4 ชุด</h3><ul>{quizletSources.map(([label, url]) => <li key={url}><a href={url} target="_blank" rel="noreferrer">{label}</a></li>)}</ul><p>คำฟินแลนด์ รูปผัน และคำอังกฤษในตารางเก็บตามชุด Quizlet คำไทย คำอธิบาย ตัวอย่างบรรยายภาพถ่าย และแบบทดสอบ Check เป็นส่วนเสริมเพื่อการเรียน ส่วนเฉลยในแท็บ Book ถอดจากหนังสือหน้า 331 และเฉลยใน Translation มาจากไฟล์ผู้สอน</p><p>ลิงก์คำคุณศัพท์ในคำสั่งเรียนและในการบ้านเป็นชุดเดียวกัน จึงรวมเพียงครั้งเดียว เนื้อหาที่เกี่ยวข้องใน section นี้ทั้งหมดอยู่ในรายการด้านบน</p><a href={moodleSource} target="_blank" rel="noreferrer">Moodle — Torstaina 1. lokakuuta SELF-STUDY LESSON</a></>}
      {(step === "Seasons" || step === "Weather" || step === "Adjectives") && <BookVocabulary section={step} speak={text => <Speak text={text} />} />}
      <div className="lesson5-footer"><button type="button" className="primary" disabled={completed.includes(step) || (step === 'Check' && !allAnswered)} onClick={finish}>{completed.includes(step) ? '✓ บันทึกว่าเสร็จแล้ว' : 'ทำส่วนนี้เสร็จแล้ว'}</button>{steps.indexOf(step) < steps.length - 1 && <button type="button" className="secondary" onClick={() => go(steps[steps.indexOf(step) + 1])}>ต่อไป: {steps[steps.indexOf(step) + 1]} <ChevronRight size={16} /></button>}</div>
      {saveError && <p role="status">บันทึกลงอุปกรณ์ไม่ได้ แต่ยังเรียนต่อในหน้านี้ได้</p>}
    </div>
  </section>;
}
