import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import './styles.css'
import { ttsService } from './services/ttsService'

beforeEach(() => {
  localStorage.clear()
  vi.restoreAllMocks()
  vi.spyOn(Math, 'random').mockReturnValue(0.999)
})

describe('App', () => {
  it('opens with an immediately understandable dictionary search', () => {
    render(<App />)
    expect(screen.getByRole('heading', { name: /understand finnish/i })).toBeInTheDocument()
    expect(screen.getByPlaceholderText(/search finnish or english/i)).toBeInTheDocument()
  })
  it('marks the dictionary as search-focused while the search keyboard is active', async () => {
    render(<App />)
    const input = screen.getByPlaceholderText(/search finnish or english/i)

    await userEvent.click(input)

    expect(input.closest('.dictionary')).toHaveClass('search-focused')
    await userEvent.tab()
    expect(input.closest('.dictionary')).not.toHaveClass('search-focused')
  })
  it('restores the mobile page when the on-screen keyboard is dismissed', async () => {
    const viewport = new EventTarget() as VisualViewport
    Object.defineProperty(viewport, 'height', { value: 800, writable: true })
    Object.defineProperty(window, 'visualViewport', { value: viewport, configurable: true })
    render(<App />)
    const input = screen.getByPlaceholderText(/search finnish or english/i)

    await userEvent.click(input)
    Object.defineProperty(viewport, 'height', { value: 400, writable: true })
    viewport.dispatchEvent(new Event('resize'))
    expect(input.closest('.dictionary')).toHaveClass('search-focused')

    Object.defineProperty(viewport, 'height', { value: 800, writable: true })
    viewport.dispatchEvent(new Event('resize'))
    await waitFor(() => expect(input.closest('.dictionary')).not.toHaveClass('search-focused'))
    Reflect.deleteProperty(window, 'visualViewport')
  })
  it('navigates to the favorites empty state', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /favorites/i })[0])
    expect(screen.getByText(/no favorites yet/i)).toBeInTheDocument()
  })
  it('flips a flashcard and advances with know or do not know', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    await waitFor(() => expect(speak).toHaveBeenCalledWith('Hei!'))
    const card = screen.getByTestId('flashcard-face')
    expect(card).toHaveTextContent('Hei!')
    expect(card).not.toHaveTextContent('Hi!')
    await userEvent.click(card)
    expect(card.querySelector('h1')).toHaveTextContent('Hei!')
    expect(card).toHaveTextContent('Hi!')
    await userEvent.click(card)
    expect(card.querySelector('h1')).toHaveTextContent('Hei!')
    expect(card).not.toHaveTextContent('Hi!')
    const knowButton = screen.getByRole('button', { name: 'Know' })
    const unknownButton = screen.getByRole('button', { name: "Don't know" })
    expect(knowButton).toHaveTextContent(/^✓$/)
    expect(unknownButton).toHaveTextContent(/^✕$/)
    expect(knowButton).toHaveClass('know')
    expect(unknownButton).toHaveClass('dont-know')
    await userEvent.click(knowButton)
    expect(screen.getByTestId('flashcard-face')).toHaveTextContent('ja')
    expect(speak).toHaveBeenCalledWith('ja')
  })
  it('adds a missed flashcard to Words to review and removes it after a correct review', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    expect(screen.getByRole('button', { name: /0 words to review/i })).toBeDisabled()
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    await userEvent.click(screen.getByRole('button', { name: "Don't know" }))
    await userEvent.click(screen.getByRole('button', { name: /close practice/i }))

    const reviewButton = screen.getByRole('button', { name: /1 word to review/i })
    expect(reviewButton).toBeEnabled()
    await userEvent.click(reviewButton)
    expect(screen.getByTestId('flashcard-face')).toHaveTextContent('Hei!')
    await userEvent.click(screen.getByRole('button', { name: 'Know' }))
    expect(screen.getByRole('heading', { name: /hienoa/i })).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: /practice again/i }))
    expect(screen.getByRole('button', { name: /0 words to review/i })).toBeDisabled()
  })
  it('opens Lesson 1 with the course alphabet audio and phrase practice', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    expect(screen.getByRole('heading', { name: /tervetuloa suomeen/i })).toBeInTheDocument()
    expect(screen.getByText(/alphabet · greetings · pronunciation/i)).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: /begin with the alphabet/i }))
    expect(screen.getByTestId('alphabet-audio')).toHaveAttribute('src', '/lesson1/004-kappale-1-aakkoset.mp3')
  })
  it('provides a comprehensive Lesson 1 knowledge check', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    await userEvent.click(screen.getByRole('tab', { name: /check/i }))
    expect(screen.getByText(/question 1 of 20/i)).toBeInTheDocument()
    expect(screen.getByText(/alphabet & sounds/i)).toBeInTheDocument()
  })
  it('includes vocabulary from printed book pages 12 and 13', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    await userEvent.click(screen.getByRole('tab', { name: /phrases/i }))
    expect(screen.getByRole('heading', { name: /book vocabulary/i })).toBeInTheDocument()
    expect(screen.getByText('suomen kurssi')).toBeInTheDocument()
    expect(screen.getByText('course day')).toBeInTheDocument()
    expect(screen.getByText('Heippa!')).toBeInTheDocument()
  })
  it('speaks Finnish content when it is clicked on the Basics page', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    await userEvent.click(screen.getByRole('tab', { name: /basics/i }))
    await userEvent.click(screen.getByRole('button', { name: 'Listen to minä' }))
    expect(speak).toHaveBeenCalledWith('minä')
  })
  it('practises matching a Finnish letter name to its sound', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    await userEvent.click(screen.getByRole('tab', { name: /sounds/i }))
    expect(screen.getByRole('heading', { name: /sound matching practice/i })).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: /play mystery sound/i }))
    expect(speak).toHaveBeenCalledWith('aa')
    await userEvent.click(screen.getByRole('button', { name: 'A' }))
    expect(screen.getByText(/oikein.*correct/i)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /next sound/i })).toBeEnabled()
  })
  it('builds a full sound-practice round covering all 29 letters', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    await userEvent.click(screen.getByRole('tab', { name: /sounds/i }))
    expect(screen.getByText('1 / 29')).toBeInTheDocument()
    expect(screen.getByText(/complete all 29 letters/i)).toBeInTheDocument()
  })
  it('includes the complete introductions and small-talk lesson with audio and translations', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /lesson 1/i })[0])
    await userEvent.click(screen.getByRole('tab', { name: /basics/i }))
    expect(screen.getByRole('heading', { name: /introductions & small talk/i })).toBeInTheDocument()
    expect(screen.getByText('What’s your name?')).toBeInTheDocument()
    expect(screen.getByText('How’s it going?')).toBeInTheDocument()
    expect(screen.getByText('Nothing special.')).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: 'Listen to Mitäs tässä' }))
    expect(speak).toHaveBeenCalledWith('Mitäs tässä')
  })
  it('splits lesson vocabulary into selectable practice groups of at most ten items', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    expect(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Vocab — Page 12 \(4\).*8 items/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Useful Phrases — Pages 12–13 \(4\).*4 items/i })).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    expect(screen.getByText('Vocab — Page 12 (1)')).toBeInTheDocument()
    expect(screen.getByText('1 of 10')).toBeInTheDocument()
  })
  it('offers number and color word groups in chunks of at most ten', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    expect(screen.getByRole('button', { name: /Numbers \(1\).*10 items/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Numbers \(3\).*9 items/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Colors \(1\).*10 items/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /Colors \(2\).*2 items/i })).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: /Numbers \(1\).*10 items/i }))
    expect(screen.getByText('Numbers (1)')).toBeInTheDocument()
    expect(screen.getByTestId('flashcard-face')).toHaveTextContent('nolla')
  })
  it('chooses a practice mode first and starts immediately when a group is selected', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    const sectionHeadings = screen.getAllByRole('heading', { level: 2 })
    expect(sectionHeadings.map((heading) => heading.textContent)).toEqual([
      'Choose your practice',
      'Choose a word group',
    ])
    expect(screen.queryByRole('button', { name: /start practice/i })).not.toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: /multiple choice/i }))
    await userEvent.click(screen.getByRole('button', { name: /Colors \(2\).*2 items/i }))
    expect(screen.getByText('Colors (2)')).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'ruskea' })).toBeInTheDocument()
  })
  it('saves a group level from first attempts only after completion', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /multiple choice/i }))
    await userEvent.click(screen.getByRole('button', { name: /Colors \(2\).*2 items/i }))
    await userEvent.click(screen.getByRole('button', { name: 'turquoise' }))
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    await userEvent.click(screen.getByRole('button', { name: 'turquoise' }))
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    await userEvent.click(screen.getByRole('button', { name: 'brown' }))
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    await userEvent.click(screen.getByRole('button', { name: /practice again/i }))

    expect(screen.getByLabelText('Level 3 of 5, latest score 50 percent')).toBeVisible()
  })

  it('does not change a group level when a session is closed early', async () => {
    localStorage.setItem('sisu:practice-progress:v1', JSON.stringify({
      reviewWords: [],
      groups: {
        'colors-2': { groupId: 'colors-2', level: 4, accuracy: 75, completedAt: '2026-09-11T10:00:00.000Z' },
      },
    }))
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /Colors \(2\).*2 items/i }))
    await userEvent.click(screen.getByRole('button', { name: 'Know' }))
    await userEvent.click(screen.getByRole('button', { name: /close practice/i }))

    expect(screen.getByLabelText('Level 4 of 5, latest score 75 percent')).toBeVisible()
  })
  it('randomizes every practice mode again whenever a group is opened', async () => {
    vi.mocked(Math.random).mockReturnValue(0)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    expect(screen.getByTestId('flashcard-face')).toHaveTextContent('ja')
    await userEvent.click(screen.getByRole('button', { name: /close practice/i }))
    vi.mocked(Math.random).mockReturnValue(0.999)
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    expect(screen.getByTestId('flashcard-face')).toHaveTextContent('Hei!')
  })
  it('speaks multiple-choice prompts and gives correct and incorrect audio feedback', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /multiple choice/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    await waitFor(() => expect(speak).toHaveBeenCalledWith('Hei!'))
    speak.mockClear()
    await userEvent.click(screen.getByRole('button', { name: /listen to hei/i }))
    expect(speak).toHaveBeenCalledWith('Hei!', expect.any(Function), expect.any(Function))
    await userEvent.click(screen.getByRole('button', { name: 'Hi!' }))
    expect(speak).toHaveBeenCalledWith('oikein')
  })
  it('builds multiple-choice alternatives only from answers in the selected group', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /multiple choice/i }))
    await userEvent.click(screen.getByRole('button', { name: /Colors \(2\).*2 items/i }))
    const choices = screen.getAllByTestId('multiple-choice-option')
    expect(choices).toHaveLength(2)
    expect(choices.map((choice) => choice.textContent).sort()).toEqual(['brown', 'turquoise'])
  })
  it('repeats missed multiple-choice words until every word is answered correctly', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /multiple choice/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    await userEvent.click(screen.getByRole('button', { name: 'and' }))
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(1)
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    for (const answer of ['and', 'Welcome!', 'Sorry! / Excuse me!', 'is …?', 'here', 'Finnish course', 'yes', 'to be', 'this']) {
      await userEvent.click(screen.getByRole('button', { name: answer }))
      await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    }
    expect(screen.getByRole('heading', { name: 'Hei!' })).toBeInTheDocument()
    expect(screen.getByText('9 of 10')).toBeInTheDocument()
    await userEvent.click(screen.getByRole('button', { name: 'Hi!' }))
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    expect(screen.getByRole('heading', { name: /hienoa/i })).toBeInTheDocument()
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(1)
  })
  it('matches one pair at a time, speaks Finnish, and fades completed pairs', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /^matching$/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    const finnishCards = screen.getAllByTestId('match-fi')
    const englishCards = screen.getAllByTestId('match-en')
    finnishCards.forEach((card, row) => {
      expect(card.dataset.matchId).not.toBe(englishCards[row].dataset.matchId)
    })
    await userEvent.click(screen.getByRole('button', { name: 'Hei!' }))
    expect(speak).toHaveBeenCalledWith('Hei!')
    await userEvent.click(screen.getByRole('button', { name: 'Hi!' }))
    expect(screen.getByRole('button', { name: 'Hei!' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Hi!' })).toBeDisabled()
  })
  it('adds both mismatched words to review and removes each correct matching pair', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /^matching$/i }))
    await userEvent.click(screen.getByRole('button', { name: /Colors \(2\).*2 items/i }))
    await userEvent.click(screen.getByRole('button', { name: 'ruskea' }))
    await userEvent.click(screen.getByRole('button', { name: 'turquoise' }))
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(2)

    await userEvent.click(screen.getByRole('button', { name: 'ruskea' }))
    await userEvent.click(screen.getByRole('button', { name: 'brown' }))
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(2)
    await userEvent.click(screen.getByRole('button', { name: 'turkoosi' }))
    await userEvent.click(screen.getByRole('button', { name: 'turquoise' }))
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(2)
  })
  it('shows typed letters inside the fill-in-the-blank prompt and ignores case', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /fill in the blank/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    expect(screen.getByTestId('live-blank')).toHaveAttribute('for', 'blank-answer')
    expect(screen.getByPlaceholderText(/type the missing/i)).toHaveAttribute('id', 'blank-answer')
    expect(screen.getByTestId('live-blank')).toHaveTextContent('_ _ _ !')
    await userEvent.type(screen.getByPlaceholderText(/type the missing/i), 'hEi!')
    expect(screen.getByTestId('live-blank')).toHaveTextContent('h E i !')
    await userEvent.click(screen.getByRole('button', { name: /check answer/i }))
    expect(screen.getByText('Correct!')).toBeInTheDocument()
  })
  it('checks fill-in answers from letters only without requiring punctuation', async () => {
    const speak = vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /fill in the blank/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    await userEvent.type(screen.getByPlaceholderText(/type the missing/i), 'HEI')
    expect(screen.getByTestId('live-blank')).toHaveTextContent('H E I !')
    await userEvent.click(screen.getByRole('button', { name: /check answer/i }))
    expect(screen.getByText('Correct!')).toBeInTheDocument()
    expect(speak).toHaveBeenCalledWith('Hei!')
    speak.mockClear()
    await userEvent.click(screen.getByRole('button', { name: /listen to hei/i }))
    expect(speak).toHaveBeenCalledWith('Hei!', expect.any(Function), expect.any(Function))
  })
  it('preserves a visibly wider gap between words in fill-in prompts', async () => {
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /fill in the blank/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    for (const answer of ['Hei', 'ja', 'Tervetuloa', 'Anteeksi', 'onko', 'täällä']) {
      await userEvent.type(screen.getByPlaceholderText(/type the missing/i), answer)
      await userEvent.click(screen.getByRole('button', { name: /check answer/i }))
      await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    }
    const prompt = screen.getByTestId('live-blank')
    expect(prompt.textContent).toContain('_   _')
    expect(getComputedStyle(prompt).whiteSpace).toBe('pre-wrap')
  })
  it('repeats missed fill-in words until every word is answered correctly', async () => {
    vi.spyOn(ttsService, 'speak').mockReturnValue(true)
    render(<App />)
    await userEvent.click(screen.getAllByRole('button', { name: /practice/i })[0])
    await userEvent.click(screen.getByRole('button', { name: /fill in the blank/i }))
    await userEvent.click(screen.getByRole('button', { name: /Vocab — Page 12 \(1\).*10 items/i }))
    await userEvent.type(screen.getByPlaceholderText(/type the missing/i), 'wrong')
    await userEvent.click(screen.getByRole('button', { name: /check answer/i }))
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(1)
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    for (const answer of ['ja', 'Tervetuloa', 'Anteeksi', 'onko', 'täällä', 'suomen kurssi', 'joo', 'olla', 'tämä']) {
      await userEvent.type(screen.getByPlaceholderText(/type the missing/i), answer)
      await userEvent.click(screen.getByRole('button', { name: /check answer/i }))
      await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    }
    expect(screen.getByTestId('live-blank')).toHaveTextContent('_ _ _ !')
    expect(screen.getByText('9 of 10')).toBeInTheDocument()
    await userEvent.type(screen.getByPlaceholderText(/type the missing/i), 'Hei')
    await userEvent.click(screen.getByRole('button', { name: /check answer/i }))
    await userEvent.click(screen.getByRole('button', { name: /continue/i }))
    expect(screen.getByRole('heading', { name: /hienoa/i })).toBeInTheDocument()
    expect(JSON.parse(localStorage.getItem('sisu:practice-progress:v1') || '{}').reviewWords).toHaveLength(1)
  })
})
